### PR TITLE
Adding partitions article

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/Viva/issues/359

@madehmer please check this is the correct location in the TOC, the article was missing from TOC

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@madehmer please help me with the review and merge, thanks

**Comment by get-itips** [comment]
@tiburd can you help me tagging someone for review and merge here? thanks

**Comment by tiburd** [comment]
Approved via email. Merging now.

**Comment by tiburd** [comment]
Closing per doc team.

**Pull request closed without merging**
