### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/Viva/issues/652

### CODE REVIEW

**Comment by scanum** [comment]
@Starshine89 
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@Starshine89
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@Starshine89
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
Link updated in another PR

**Pull request closed without merging**
