### PR TITLE
Update be-resources.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/Viva/issues/296
Fixed link

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@madehmer 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@madehmer
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@madehmer
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
change already incorporated into article.

**Pull request closed without merging**
