### PR TITLE
Update viva-insights-my-org.md

### PR DESCRIPTION
**Pull request by soyalejolopez**
Include details on "My Organization" tab requirements.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by soyalejolopez** [comment]
Hi @madehmer and @scanum , any news on this one getting published to the main branch?

**Comment by scanum** [comment]
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
closing due to inactivity

**Pull request closed without merging**
