### PR TITLE
Update linkedin-learning-free-courses.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/Viva-pr/issues/6724.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@bhaswatic 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@bhaswatic
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@bhaswatic
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by lizap** [comment]
Article has been updated to no longer list specific courses. Thanks!

**Pull request closed without merging**
