### PR TITLE
clarify

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/Viva/issues/424

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@bhaswatic PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by bhaswatic** [comment]
Hi all, 
As per the Magic Content team process - I will create a new PR to incorporate these changes and close this when I am done. 
Bhas

**Comment by tiburd** [comment]
> Hi all, As per the Magic Content team process - I will create a new PR to incorporate these changes and close this when I am done. Bhas

@bhaswatic 
Please do not close this PR. This PR was created by one of our freelance reviewers to resolve a customer-submitted issue.

**Review by bhaswatic — APPROVED** [review]
Looks good to me.

**Comment by bhaswatic** [comment]
@tiburd - Thank you for the clarification. I now see that my action here is as a reviewer, and not a publisher. I've approved the content changes.

**Pull request merged**
