### PR TITLE
Fixed invalid link

### PR DESCRIPTION
**Pull request by kalleantero**
How to Make Sure Agile Teams Can Work Together link was pointing to https://insights.office.com/collaboration/how-to-make-sure-agile-teams-can-work-together/ and site certificate was expired. I think this https://workplaceinsights.microsoft.com/collaboration/how-to-make-sure-agile-teams-can-work-together/ should we the right location.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@madehmer 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@madehmer 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@madehmer
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by lizap** [comment]
This content has been retired - thank you!

**Pull request closed without merging**
