### PR TITLE
Update configure-sharepoint-content-source.md

### PR DESCRIPTION
**Pull request by getalex**
Site Column 'Duration' is defined at global level, if customer uses Content Type Hub or other global reuse tool for site columns the name 'Duration' will be problematic - need to keep consistent and name the column 'ContentDuration' to avoid collision with internal SharePoint column names.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@bhaswatic 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by getalex** [comment]
Finalizing edits.

**Comment by getalex** [comment]
Looking to merge changes made to list column Duration --> ContentDuration @bhaswatic let me know if you need addtl context.

**Review by getalex — COMMENTED** [review]
Included quote for emphasis on column name as is done in others for consistency.

**Pull request merged**
