### PR TITLE
Update eac-key-admin-roles-permissions.md

### PR DESCRIPTION
**Pull request by Starshine89**
2 minor changes: Removed "Yammer" instance and a checkmark that was incorrect, per Shreya Naya's request.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Graciela985** [comment]
Okay madam , i can fix it sir

**Comment by Graciela985** [comment]
Okay madam , i can fix it madam

**Comment by scanum** [comment]
@EstherGaddindla 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@mamiepjohnson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by Graciela985** [comment]
> @mamiepjohnson 
> PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

Okay Madam, we can fix it.!!!

**Comment by Graciela985** [comment]
> 2 minor changes: Removed "Yammer" instance and a checkmark that was incorrect, per Shreya Naya's request.

Okay Madam, we can fix it.!!!

**Comment by Graciela985** [comment]
Yes Madam, I can fix it...

**Comment by scanum** [comment]
@mamiepjohnson
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by Starshine89 — COMMENTED** [review]
This edit is no longer needed.

**Comment by Starshine89** [comment]
This change is from May 2023 and is no longer needed or relevant.

**Pull request closed without merging**
