### PR TITLE
Removed ".md" in links to other docs

### PR DESCRIPTION
**Pull request by loryanstrant**
Links were giving a 404 as the .md extension is not used on the Learn site.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@lilyolason 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by loryanstrant** [comment]
Is this being merged any time soon?

**Comment by scanum** [comment]
@lilyolason
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@loryanstrant hope all is well. I don't have permissions to merge, I tagger the author again to help us with merging. Thanks.

**Pull request closed without merging**
